### ISSUE TITLE
FACT1 - Factorial

### ISSUE THREAD

**Issue by grvashu** [grvashu/pset.old#11]
Write a computer program to read an integer N and print its factorial.

**Test Case**
Input: 3
Output: 6

**How to read an input in P5JS?**
https://p5js.org/examples/dom-input-and-button.html

**What is Factorial?**
In mathematics, the factorial of a non-negative integer n, denoted by n!, is the product of all positive integers less than or equal to n. For example, 
![image](https://user-images.githubusercontent.com/2363826/36246663-d85120ea-1256-11e8-8df1-9e90bc6ab207.png)

The value of 0! is 1, according to the convention for an empty product.

**Comment by remus-lupin** [comment]
@apoorva-a98 Your program does not produce any output on the canvas.
