### ISSUE TITLE
SHRM1- Simple Harmonic Motion

### ISSUE THREAD

**Issue by grvashu** [grvashu/pset.old#12]
In mechanics and physics, simple harmonic motion is a special type of periodic motion or oscillation motion where the restoring force is directly proportional to the displacement and acts in the direction opposite to that of displacement.

Simple harmonic motion can serve as a mathematical model for a variety of motions, such as the oscillation of a spring. In addition, other phenomena can be approximated by simple harmonic motion, including the motion of a simple pendulum as well as molecular vibration.

Sketch as shown in this [link](https://en.wikipedia.org/wiki/Simple_harmonic_motion#/media/File:Simple_Harmonic_Motion_Orbit.gif) through P5JS program.

You can display text in P5JS by using text() function.
`text("text-to-display",x,y)`

**Comment by remus-lupin** [comment]
@simraan9 @apoorva-a98 Your solution does not resemble the animation shown in the above link.
