### ISSUE TITLE
ADDR1 - 1 Bit Half Adder

### ISSUE THREAD

**Issue by grvashu** [grvashu/pset.old#4]
In electronics, a logic gate is an idealized or physical device implementing a Boolean function; that is, it performs a logical operation on one or more binary inputs and produces a single binary output. There are two sets of symbols for elementary logic gates in common use, both defined in ANSI/IEEE Std 91-1984 and its supplement ANSI/IEEE Std 91a-1991. The "distinctive shape" set, based on traditional schematics, is used for simple drawings and derives from MIL-STD-806 of the 1950s and 1960s. It is sometimes unofficially described as "military", reflecting its origin. The "rectangular shape" set, based on ANSI Y32.14 and other early industry standards, as later refined by IEEE and IEC, has rectangular outlines for all types of gate and allows representation of a much wider range of devices than is possible with the traditional symbols. The IEC standard, IEC 60617-12, has been adopted by other standards, such as EN 60617-12:1999 in Europe, BS EN 60617-12:1999 in the United Kingdom, and DIN EN 60617-12:1998 in Germany.

![image](https://user-images.githubusercontent.com/2363826/36215776-05eddeaa-11d3-11e8-8d63-1699af4d227b.png)

![image](https://user-images.githubusercontent.com/2363826/36215818-24d1ea00-11d3-11e8-8255-61123ff255a2.png)

Design 1-bit half adder using the minimum number of logic gates. The half adder adds two single binary digits A and B. It has two inputs A and B and two outputs, sum (S) and carry (C). The carry signal represents an overflow into the next digit of a multi-digit addition. The value of the sum is 2C + S.
![image](https://user-images.githubusercontent.com/2363826/36215852-3e184568-11d3-11e8-8a84-c2a5bccca990.png)

**Comment by simraan9** [comment]
![image](https://user-images.githubusercontent.com/22179784/36324929-0c8fa48c-137c-11e8-8d96-e54dce12354f.png)
