### ISSUE TITLE
FUNC1 - Functions

### ISSUE THREAD

**Issue by grvashu** [grvashu/pset.old#9]
In mathematics, a function is a relation between a set of inputs and a set of permissible outputs with a property that each input related to exactly one output. An example is a function that relates to each real number x to its square x^2. The output of a function f corresponding to an input x is denoted by f(x) (read as "f of x"). In this example, if the input is -3, then the output is 9, and we may write f(-3)=0. The input variable(s) are sometimes referred to as the argument(s) of the function.

![image](https://user-images.githubusercontent.com/2363826/36246441-d8f72cc0-1255-11e8-9633-4cb82f7cf31c.png)

Zero of function, also called as root, of a real-, complex- or generally vector-valued function f is a member x of the domain of f such that f(x) vanishes at x; that is

x such that f(x) = 0

Find at least one zero for each of the following functions:
![image](https://user-images.githubusercontent.com/2363826/36246452-e682c8ea-1255-11e8-8416-0342cdff43df.png)

**Comment by simraan9** [comment]
![image](https://user-images.githubusercontent.com/22179784/36324439-809dfeca-137a-11e8-9ab9-62c9d80c0456.png)

I'm not sure this is the right way and place to upload the image, but here's a shot.
